minimumReleaseAge: 4320
blockExoticSubdeps: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200
minimumReleaseAgeExclude:
  - '@gingacodemonkey/config'
strictDepBuilds: true
allowBuilds:
  'unrs-resolver': true
