name: CI Tests

on:
  pull_request:
    branches:
      - master
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-runner:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/actions/setup

      - name: Test
        run: pnpm run test
